### ISSUE TITLE
Backing up to an S3 bucket in a different AWS account using IRSA

### ISSUE THREAD

**Issue by mijndert** [vmware-tanzu/velero-plugin-for-aws#65]
Currently I'm using IRSA on my EKS cluster, I have setup a serviceAccount:

```
serviceAccount:
  server:
    create: true
    name: velero
    annotations: 
       eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/role-velero
```

For redundancy I want to be able to create a second backupStorageLocation in a different AWS account, with a different backup schedule. 

I can set up cross-account access: https://aws.amazon.com/blogs/containers/cross-account-iam-roles-for-kubernetes-service-accounts/

But I found no way of passing on multiple roles to Velero to make this happen.

What would be the best way to make cross-account backups to S3 happen?
